version: "3"
services:
  server:
    container_name: area-server
    build: ./server
    ports:
    - "8080:8080"
    environment:
      APP_PORT: 8080
    volumes:
      - ./server:/app

  mongo:
    image: mongo:latest
    container_name: area-db
    restart: on-failure
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
     - .docker/:/docker-entrypoint-initdb.d/init-mongo.sh
     - mongodb_data:/data/db  # Ajout du volume pour stocker les données MongoDB

volumes:
  mongodb_data:
