version: "3"
services:
  server:
    container_name: area-server
    build: ./server
    ports:
    - "8080:8080"
    environment:
      APP_PORT: 8080
    volumes:
      - ./server:/app
  client_mobile:
    build: ./client/mobile
    volumes:
      - ./client:/app

  client_web:
    build: ./client/web
    container_name: area-client
    volumes:
      - ./client:/app
    depends_on:
      - client_mobile
      - server
    ports:
    - "8081:8081"
    environment:
      APP_PORT: 8081

  mongo:
    image: mongo:latest
    container_name: area-db
    restart: on-failure
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
     - .docker/:/docker-entrypoint-initdb.d/init-mongo.sh